apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - github.com/kubernetes-sigs/descheduler/kubernetes/cronjob?ref=release-1.35

patches:
  - path: cronjob-patch.yaml

configMapGenerator:
  - name: descheduler-policy
    files:
      - policy.yaml
