---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage

resources:
  - deployment.yaml
  - rbac.yaml
  - secret.yaml
  - service-account.yaml
  - service.yaml
  - httproute.yaml

configMapGenerator:
  - name: homepage
    files:
      - config/bookmarks.yaml
      - config/kubernetes.yaml
      - config/services.yaml
      - config/settings.yaml
      - config/widgets.yaml
      - config/docker.yaml
