---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-redirect-grafana
spec:
  parentRefs:
    - name: cilium-shared-gateway
      namespace: kube-system
      sectionName: http
  hostnames:
    - grafana.g2net.xyz
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
