---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-admin-credentials
spec:
  encryptedData:
    admin-password: AgC6ePaSnvVLF9UoH6LVnW5Q4JbaE2Y7NK7QlQnIfIs7kYO7KAtvpTZmjICm1ZmadxveTAPj8tZTSulvBpt46E4rPNI3CctBAGA1RjYNsQfNe1wHcyHxud5XU5MvTahbYQDdnWWsdj5DqgoYQDIIX2Alpfbb67DdvmKiTW8ZjP4LMSc1ajifDszK1rcfFERUtOSrYG2CCdi8wzsrOZ3lZJDHJNhOnWACASfMJ7LnweK5qrc334O8VoVQsOAawAvjAxMigs9akH1Ptc/8kqNWT32Ny5z8E/doCHkl/CVheGCh4OmkapoOq4i4btovBFphusP6K1Rz6xNL+zCDmN8LNzq1ZmeFs5mfTFookRbqC8LAIZP9pbwY0BXRs8ecrj5hzFTG1D3LVPFfvsTNN0XuO02VIBE2JdPtLljCHCGfji9Uq6olFNIWx/5tzVJEbYvZYQa/ULBnmReYQqiRIRo0mXSqYsHGAHQJIWhmEtnpasAZUMifYlzvbrcSNWYFeMhzjbaDgQpuyAZB2oA7BE2znKsKl8R4cjnBcKYdV66X4k34EdUPm3ut0Q3B5rmf2Lfw77HmCr/dteAvWFTHBWgUg7e/x8daqLKwX9kP75nqQ4SU2D78aimr2cHZHbj+AdTnQNl0ZMq43BeeEhdKevEl6IGyrprTN0t5pu83fJPtGu27oUqspykhXyI70hyyemJXIxf59gEhGHJafCAK
    admin-user: AgBgUWSJ8xH8Bl7tqq1z0ZyUKC4hTdTJ38K92FeEnEODcx2BPxz/giWWI554rMSwBEpV3zb50zeCF3bTNM33Ex8Wmcce13AYPAipxQVF9VSDcgyk/kkIkiEg+QOPYDY8b3K5zfPVMbenvSqS+1x9Wtixho6iuvueW/rpDpMB+0bwS2Mkk/bCBU5LuGWUJDXyfA4Me8CSvlgYsE+hy6LMKnNeCGFFoU29ImNBNLA0p40fYVLEpEndFtLa80lUIIpW8xLnN1KNoqDLwL0jFL2vNmNwJk+VGhnbc/2f1CoVwUAKAWP12s7RrdrdhigFR84DXTa1v+jv6LPW8u0nrkvyJh6HrBsBBSL0OisKfvpQZ3yghf+1Gb0RSfPC5cl9RCKOSiOSqvwzaeCyFe33EmNDut/s5o0LLsj3BOKmFCivFS5JFYDh/PSQ7gW0BuR+2yKboX/BtyxRUYQNZNJ2Z/DVDznyRB5i/sIaiuZP5NnAcNFA4x410eRkuAu/34mTanwkRLGAXy/l673wYB8eyE+3ur67nI5/0AEQKL0bhu2dMlKfuHKU/bzqaSUXI4dsE+tRGdDmZKR/cSXdyWXnImggNWka7kwKMBvJd0dLofKP0K8Rp/wpPdTo+W1ZLYLN5akkKkGPk42jY58yazBGXU9i4dPkosQWMUgzjaMkf/ohI64LliNrMFVreTDRbB9ZzUFYIF25XzIqkA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-admin-credentials
    type: Opaque
