---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: k8s-monitoring
    repo: https://grafana.github.io/helm-charts
    namespace: observability
    version: 3.8.0
    releaseName: k8s-monitoring
    includeCRDs: true
    valuesFile: values.yaml
