---
cluster:
  name: k3s-homelab

destinations:
  - name: loki
    type: loki
    url: http://loki-gateway/loki/api/v1/push
  - name: prometheus
    type: prometheus
    url: http://prometheus-operated:9090/api/v1/write
  - name: tempo
    type: otlp
    url: http://tempo:4317
    tls:
      insecure: true
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true
  - name: pyroscope
    type: pyroscope
    url: http://pyroscope:4040

clusterMetrics:
  enabled: true
  global:
    scrapeInterval: 30s
  node-exporter:
    enabled: true
    deploy: true
    metricsTuning:
      useDefaultAllowList: false
  kubelet:
    metricsTuning:
      useDefaultAllowList: false
  cadvisor:
    metricsTuning:
      useDefaultAllowList: false
  apiServer:
    enabled: true

clusterEvents:
  enabled: true

nodeLogs:
  enabled: true

podLogsViaKubernetesApi:
  enabled: true

annotationAutodiscovery:
  enabled: true
  scrapeInterval: 30s

autoInstrumentation:
  enabled: true
  beyla:
    config:
      data:
        ebpf:
          enable_context_propagation: true
          traffic_control_backend: tcx
          disable_blackbox_cp: true
          track_request_headers: true

applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
  conectors:
    spanLogs:
      enabled: true

prometheusOperatorObjects:
  enabled: true

# profiling enabled via annotations:
# ebpf - profiles.grafana.com/cpu.ebpf.enabled="true"
# java - profiles.grafana.com/java.enabled="true"
# pprof - profiles.grafana.com/cpu.scrape: "true"
# pprof - profiles.grafana.com/cpu.port: port
# pprof - profiles.grafana.com/cpu.port_name: port_name
# pprof - profiles.grafana.com/cpu.scheme: scheme
# pprof - profiles.grafana.com/cpu.container: container
profiling:
  enabled: true

alloy-receiver:
  enabled: true

alloy-profiles:
  enabled: true

alloy-metrics:
  enabled: true

alloy-singleton:
  enabled: true

alloy-logs:
  enabled: true
  alloy:
    clustering:
      enabled: true

alloy-operator:
  deploy: true
  waitForAlloyRemoval:
    enabled: false
