---
cluster:
  name: k3s-homelab

destinations:
  - name: loki
    type: loki
    url: http://loki-gateway/loki/api/v1/push
  - name: prometheus
    type: prometheus
    url: http://prometheus-operated:9090/api/v1/write
  - name: tempo
    type: otlp
    url: http://tempo:4317
    tls:
      insecure: true
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true
  - name: pyroscope
    type: pyroscope
    url: http://pyroscope:4040

  - name: logforwarder
    type: otlp
    url: http://127.0.0.1:14317
    tls:
      insecure: true
    auth:
      type: "none"
    metrics: { enabled: false }
    logs:    { enabled: true  }
    traces:  { enabled: false }

clusterMetrics:
  enabled: true
  global:
    scrapeInterval: 30s
  node-exporter:
    enabled: true
    deploy: true
    metricsTuning:
      useDefaultAllowList: false
  kubelet:
    metricsTuning:
      useDefaultAllowList: false
  cadvisor:
    metricsTuning:
      useDefaultAllowList: false
  apiServer:
    enabled: true

clusterEvents:
  enabled: true

nodeLogs:
  enabled: true

podLogs:
  destinations:
    - loki
    - logforwarder
  enabled: true

annotationAutodiscovery:
  enabled: true
  scrapeInterval: 30s

autoInstrumentation:
  enabled: true
  beyla:
    config:
      data:
        ebpf:
          enable_context_propagation: true
          traffic_control_backend: tcx
          disable_blackbox_cp: true
          track_request_headers: true

applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
  conectors:
    spanLogs:
      enabled: true

prometheusOperatorObjects:
  enabled: true

# profiling enabled via annotations:
# ebpf - profiles.grafana.com/cpu.ebpf.enabled="true"
# java - profiles.grafana.com/java.enabled="true"
# pprof - profiles.grafana.com/cpu.scrape: "true"
# pprof - profiles.grafana.com/cpu.port: port
# pprof - profiles.grafana.com/cpu.port_name: port_name
# pprof - profiles.grafana.com/cpu.scheme: scheme
# pprof - profiles.grafana.com/cpu.container: container
profiling:
  enabled: true

alloy-receiver:
  enabled: true

alloy-profiles:
  enabled: true

alloy-metrics:
  enabled: true

alloy-singleton:
  enabled: true

alloy-logs:
  enabled: true
  includeDestinations:
    - logforwarder
  alloy:
    stabilityLevel: experimental
    envFrom:
    - secretRef:
        name: aws-creds
  extraConfig: |-
    otelcol.receiver.otlp "default" {
      grpc {
        endpoint = "127.0.0.1:14317"
      }
      http {
        endpoint = "127.0.0.1:14318"
      }

      output {
        logs =  [otelcol.processor.filter.media.input]
      }
    }

    otelcol.processor.filter "media" {
      error_mode = "ignore"

        logs {
          log_record = [
            `resource.attributes["k8s.namespace.name"] != "media"`,
          ]
        }

      output {
        logs    = [otelcol.exporter.awss3.logs.input]
      }
    }

    otelcol.exporter.awss3 "logs" {
      s3_uploader {
        region = "eu-north-1"
        s3_bucket = "gedas-test-logs-bucket"
        s3_prefix = "logs"
        s3_partition_format = "%Y-%m-%d"
        compression = "gzip"
      }
      resource_attrs_to_s3 {
        s3_prefix = "service.name"
      }
    }

alloy-operator:
  deploy: true
  waitForAlloyRemoval:
    enabled: false

integrations:
  cert-manager:
    instances:
      - name: cert-manager
        namespace: kube-system
        labelSelectors:
          app.kubernetes.io/name: cert-manager
  alloy:
    instances:
      - name: alloy-logs
        namespace: observability
        labelSelectors:
          app.kubernetes.io/name: alloy-logs
      - name: alloy-metrics
        namespace: observability
        labelSelectors:
          app.kubernetes.io/name: alloy-metrics
      - name: alloy-receiver
        namespace: observability
        labelSelectors:
          app.kubernetes.io/name: alloy-receiver
      - name: alloy-profiles
        namespace: observability
        labelSelectors:
          app.kubernetes.io/name: alloy-profiles
      - name: alloy-singleton
        namespace: observability
        labelSelectors:
          app.kubernetes.io/name: alloy-singleton
  grafana:
    instances:
      - name: grafana
        namespace: observability
        labelSelectors:
          app.kubernetes.io/name: grafana
  loki:
    instances:
      - name: loki
        namespace: observability
        labelSelectors:
          app.kubernetes.io/name: loki
  tempo:
    instances:
      - name: tempo
        namespace: observability
        labelSelectors:
          app.kubernetes.io/name: tempo
