---
pyroscope:
  persistence:
    enabled: true
    existingClaim: pyroscope-pvc
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - pi

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack

alloy:
  enabled: false
