---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maistokainos

resources:
  - sealed-secret.yaml
  - pvc.yaml
  - deployment.yaml
  - cronjob.yaml
  - service.yaml
  - cf-tunnel.yaml
