---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thelounge
  labels:
    app: thelounge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thelounge
  template:
    metadata:
      labels:
        app: thelounge
    spec:
      containers:
        - name: thelounge
          image: thelounge/thelounge:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: data
              mountPath: /var/opt/thelounge
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: thelounge-data
