---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backup

helmCharts:
  - name: k8up
    repo: https://k8up-io.github.io/k8up
    namespace: backup
    version: 4.8.6
    releaseName: k8up
    valuesFile: values.yaml

resources:
  - sealed-secret.yaml
  - https://github.com/k8up-io/k8up/releases/download/k8up-4.8.6/k8up-crd.yaml
