---
extraVolumes:
  - name: tempo-storage
    persistentVolumeClaim:
      claimName: tempo-pvc

tempo:
  extraVolumeMounts:
    - name: tempo-storage
      mountPath: /var/tempo
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://prometheus-operated:9090/api/v1/write
  retention: "72h"

  overrides:
    defaults:
      metrics_generator:
        processors:
          - local-blocks

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
                - pi
